#!/bin/bash
#
# setup-before-tests
#
# The purpose of this script is to prepare a Drupal site to run
# the behat tests on.
#
# Usage:
#
#    compser install
#    ./bin/setup-before-tests
#    ./bin/behat
#

SELF_DIRNAME="`dirname -- "$0"`"
PROJECT_BASE_DIR="`cd -P -- "$SELF_DIRNAME/.." && pwd -P`"

# Set up our $PATH
export PATH="$PROJECT_BASE_DIR/bin:$HOME/bin:$PATH"

install-drupal
start-webserver
wait-for-webserver
